const ObjectID = require('mongodb').ObjectID;

const albums = [
  {
    name: "Pink Friday",
    picture:
      "https://urbanislandz.com/wp-content/uploads/2010/10/Nicki-Minaj-Pink-Friday-Album-Cover1.jpg",
    songs: [
      "I'm The Best",
      "Roman's Revenge (featuring Eminem)",
      "Did It On 'Em",
      "Right Thru Me",
      "Fly (featuring Rihanna)",
      "Save Me",
      "Moment 4 Life (featuring Drake)",
      "Check It Out (featuring will.i.am)",
      "Blazin (featuring Kanye West)",
      "Here I Am",
      "Dear Old Nicki",
      "Your Love",
      "Last Chance (featuring Natasha Bedingfield)",
      "Super Bass",
      " Blow Ya Mind",
      "Muny",
      "Girls Fall Like Dominoes [Bonus Track]",
    ],
    artist: "Nicki Minaj",
    creatorId: new ObjectID(0)
  },
  {
    name: "Traumazine",
    picture:
      "https://cdn-www.konbini.com/files/2022/08/Megan-Thee-Stallion-Traumazine.jpg",
    songs: [
      "NDA",
      "Ungrateful feat. Key Glock",
      "Not Nice",
      "Budget feat. Latto",
      "Her",
      "Gift & Curse",
      "Ms. Nasty",
      "Who Me feat. Pooh Shiesty",
      "Red Wine",
      "Scary feat. Rico Nasty",
      "Anxiety",
      "Flip Flop",
      "Consistency feat. Jhené Aiko",
      "Star feat. Lucky Daye",
      "Pressurelicious feat. Future",
      "Plan B",
      "Southside Royalty Freestyle feat. Sauce Walka, Big Pokey, and Lil Keke",
      "Sweetest Pie feat. Dua Lipa",
    ],
    artist: "Megan Thee Stallion",
    creatorId: new ObjectID(0)
  },
  {
    name: "The Miseducation of Lauryn Hill",
    picture: "https://upload.wikimedia.org/wikipedia/en/5/55/LaurynHillTheMiseducationofLaurynHillalbumcover.jpg",
    songs: [
      "Intro",
      "Lost Ones",
      "Ex-Factor",
      "To Zion",
      "Doo Wop (That Thing)",
      "Superstar",
      "Final Hour",
      "When It Hurts So Bad",
      "I Used to Love Him",
      "Forgive Them Father",
      "Every Ghetto, Every City",
      "Nothing Even Matters",
      "Everything Is Everything",
      "The Miseducation of Lauryn Hill"	
    ],
    artist: "Lauryn Hill",
    creatorId: new ObjectID(0)    
  },
  {
    "artist": "Doja Cat",
    "name" : "Amala",
    "picture": "https://upload.wikimedia.org/wikipedia/en/b/b9/Dojacatamala.png",
    "songs" : ["Go To Town",
    "Cookie Jar",
    "Roll With Us",
    "Wine Pon You",
    "Fancy",
    "Wild Beach",
    "Morning Light",
    "Candy",
    "Game",
    "Casual",
    "Down Low",
    "Body Language",
    "All Nighter"]
  },
  {
    name: "Invasion of Privacy",
    picture: "https://en.wikipedia.org/wiki/Invasion_of_Privacy_%28album%29",
    songs: [
      "Get Up",
      "Drip",
      "Bickenhead",
      "Bodak Yellow",
      "Be Careful [Explicit]",
      "Best Life",
      "I Like It [Explicit]",
      "Ring",
      "Money Bag",
      "Bartier Cardi",
      "She Bad",
      "Thru Your Phone",
      "I Do",
    ],
    artist: "Cardi B",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Ms. G.O.A.T.",
    picture: "https://upload.wikimedia.org/wikipedia/en/3/33/Msgoatalbum.png",
    songs: [
      "Hood Newz: Lil' Kim Free",
      "Ms. G.O.A.T.",
      "Mis-Education of Lil' Kim",
      "I Get It",
      "Wrath of Kim's Madness",
      "Chillin' Tonite",
      "Need a Bitch",
      "2 Hatin' Bitches (Skit)",
      "It's Kim Bitches (Get That Money)",
      "Fuck You",
      "Rock on Wit Yo Bad Self",
      "Queen Bitch 101",
      "Kim Gets Deeper",
      "Wanna Lick (Magic Stick, Pt. 2)",
      "Thang on Me",
      "It Ain't My Fault",
      "Kimmy More",
      "Salute the Women of Hip Hop (Skit)",
      "Let It Go",
      "Mr. Cee Speaks",
      "Freaky Gurl (Remix)",
      "Outro",
      "No One (Remix)",
    ],
    artist: "Lil Kim'",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Miss E... So Addictive",
    picture: "https://upload.wikimedia.org/wikipedia/en/e/e4/Missy_Elliott-Miss_E._So_Addictive.jpg",
    songs: [ 
      "...So Addictive (intro)",
      "Dog in Heat",
      "One Minute Man",
      "Lick Shots",
      "Get Ur Freak On",
      "Scream a.k.a. Itchin'",
      "Old School Joint",
      "Take Away",
      "4 My People",
      "Bus-A-Bus",
      "Whatcha Gon' Do",
      "Step Off",
      "X-Tasy",
      "Slap! Slap! Slap!",
      "I've Changed (interlude)",
      "One Minute Man (remix)",
      "[silence]",
      "Higher Ground (prelude)",
      "Higher Ground",
    ],
    artist: "Missy Elliott",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Big Latto",
    picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRdpJ67VMeSHIbYGD9mS6o5SU8e7urz3txx2xpYvw&usqp=CAE&s",
    songs: [
      "ATL Hoe",
      "Bitch From Da Souf",
      "HYS",
      "Bounce",
      "Pretty Ricky",
      "Longway",
    ],
    artist: "Latto",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Nightmare Vacation",
    picture: "https://upload.wikimedia.org/wikipedia/en/a/a9/Rico_Nasty_-_Nightmare_Vacation.jpg",
    songs: [
      "Candy",
      "Don’t Like Me",
      "Check Me Out",
      "IPHONE",
      "STFU",
      "Back & Forth",
      "Girl Scouts",
      "Let It Out",
      "Loser",
      "No Debate",
      "Pussy Poppin",
      "OHFR?",
      "10Fo",
      "Own It",
      "Smack a Bitch (remix)",
      "Smack a Bitch",
    ],
    artist: "Rico Nasty",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Scorpion",
    picture: "https://en.wikipedia.org/wiki/File:Scorpion_-_Eve_-_Cover.jpg",
    songs: [
      "Cowboy",
      "Who's That Girl? [Clean]",
      "Let Me Blow Ya Mind [Clean]",
      "You Had Me, You Lost Me",
      "Got What You Need",
      "Gangsta B's",
      "That's What It Is",
      "Scream Double R",
      "Thug In The Street",
      "No, No, No",
      "You Ain't Gettin' None",
      "Life Is So Hard",
      "Be Me",
    ],
    artist: "Eve",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Queen Elizabitch",
    picture: "https://i1.sndcdn.com/avatars-000568600275-ba3lgg-t500x500.jpg",
    songs: [
      "Scraps",
      "33rd",
      "CPR",
      "Author",
      "Quick Thought",
      "Biggie Smalls",
      "Barcodes",
      "Cumshot",
      "Civilized",
      "Toys "R" Us",
      "Tarzan",
      "Reality, Pt. 4",
    ],
    artist: "Cupcakke",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Kala",
    picture: "https://upload.wikimedia.org/wikipedia/en/c/cf/M.I.A._-_Kala.png",
    songs: [
      "Bamboo Banga",
      "Bird Flu",
      "Boyz",
      "Jimmy",
      "Hussel",
      "Mango Pickle Down River",
      "20 Dollar",
      "World Town",
      "The Turn",
      "XR2",
      "Paper Planes",
      "Come Around",
    ],
    artist: "M.I.A",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Ho, Why Is You Here?",
    picture: "https://media.pitchfork.com/photos/5f3aa032eb982d18c453e0b0/1:1/w_3000,h_3000,c_limit/Ho,%20Why%20Is%20You%20Here?_flo%20milli.jpg",
    songs: [
      "Mood Everyday (Intro)",
      "Beef FloMix",
      "Like That B*tch",
      "In The Party",
      "Pockets Bigger",
      "Weak",
      "Send The Addy",
      "May I",
      "Pussycat Doll",
      "Not Friendly",
      "Scuse Me",
    ],
    artist: "Flo Milli",
    creatorId: new ObjectID(0)    
  },
  {
    name: "High Maintenance",
    picture: "https://upload.wikimedia.org/wikipedia/en/d/d4/Saweetie_-_High_Maintenance.jpg",
    songs: [
      "Intro",
      "B.A.N.",
      "Agua",
      "Good Good",
      "Icy Grl",
      "High Maintenance",
      "23",
      "Respect",
      "Too Many",
    ],
    artist: "Saweetie",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Dans ma bulle",
    picture: "https://i.ytimg.com/vi/Kti9qZURQHo/maxresdefault.jpg",
    songs: [
      "Introduction",
      "La Boulette (Génération nan nan)",
      "Ma France à moi",
      "Feuille blanche",
      "Jeune demoiselle",
      "Car tu portes mon nom",
      "Marine (Version 2006)",
      "Dans ma bulle",
      "Par amour",
      "Big Up",
      "Confessions nocturnes",
      "T.S.",
      "Me revoilà (avec Jacky Brown)",
      "Cause à effet (Version 2006)",
      "Petite banlieusarde",
    ],
    artist: "Diam's",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Jour avant caviar",
    picture: "https://i.scdn.co/image/ab67616d0000b27323d6afba931b724fd3347d27",
    songs: [
      "TCQDOF",
      "Inanimée",
      "Beni",
      "La brume",
      "AH LALA",
      "Coucou",
      "15 AM",
      "Billets",
      "Désolé",
      "Johnny",
      "Wollan (Bonus track)",
      "Comme à la maison ",
    ],
    artist: "Meryl",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Queen's Speech",
    picture: "https://is5-ssl.mzstatic.com/image/thumb/Music125/v4/b5/4e/80/b54e808c-8a18-8fd1-3b90-4ac6ae68100b/qs-image-resize-1450x1450-5685bc5a33de5-large.jpg/600x600bf-60.jpg",
    songs: [
      "Lukatar",
      "Queen's Speech 1",
      "Queen's Speech 2",
      "Queen's Speech 3",
      "Queen's Speech 4",
    ],
    artist: "Lady Leshurr",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Rumours",
    picture: "https://i1.sndcdn.com/artworks-3dDFEp7j4wf4-0-t500x500.jpg",
    songs: [
      "Rumours"
    ],
    artist: "Ivorian Doll",
    creatorId: new ObjectID(0)    
  },
  {
    name: "Antidote",
    picture: "https://i.scdn.co/image/ab67616d0000b2739423815468582a8e6bc1807c",
    songs: [
      "Jolie",
      "Liquide",
      "Amour & désastres",
      "Désillusions",
      "Même pas bonne",
      "Notif",
      "Prends ton time",
      "Oh oui",
      "Pleurer",
      "Ich Liebe Dich",
      "Coeur Wanted",
      "Villa",
      "BXL",
      "Cocorico (Bonus)",
    ],
    artist: "Shay",
    creatorId: new ObjectID(0)    
  },
  {
    name: "NAKAMURA",
    picture: "https://i.scdn.co/image/ab67616d0000b2739922157daa474131bb3a0fbc",
    songs: [
      "La dot",
      "Djadja",
      "Pompom",
      "Copines",
      "Pookie",
      "Ça fait mal",
      "Faya",
      "Gangster",
      "Sucette",
      "Whine Up",
      "Gang",
      "Dans ma bulle",
      "Oula",
    ],
    artist: "Aya Nakamura",
    creatorId: new ObjectID(0)    
  }
];

module.exports = albums;
